name: project_management_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  introduction_screen:
  provider: ^6.0.1
  motion_tab_bar: ^2.0.4
  flutter_svg:
  water_drop_nav_bar: ^2.2.1
  firebase_core: ^3.1.1
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  firebase_storage:
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/